// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PukiAPI.Data;

#nullable disable

namespace PukiAPI.Migrations
{
    [DbContext(typeof(PUKIDbContext))]
    [Migration("20250717132105_seeding dta")]
    partial class seedingdta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PukiAPI.Models.Domain.Predmet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ESPB")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Predmeti");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            ESPB = 0,
                            Naziv = "Matematika 1"
                        },
                        new
                        {
                            Id = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            ESPB = 0,
                            Naziv = "Matematika 2"
                        },
                        new
                        {
                            Id = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3"),
                            ESPB = 0,
                            Naziv = "Programiranje"
                        },
                        new
                        {
                            Id = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4"),
                            ESPB = 0,
                            Naziv = "Baze Podataka"
                        },
                        new
                        {
                            Id = new Guid("a5a5a5a5-a5a5-a5a5-a5a5-a5a5a5a5a5a5"),
                            ESPB = 0,
                            Naziv = "Web Programiranje"
                        },
                        new
                        {
                            Id = new Guid("a6a6a6a6-a6a6-a6a6-a6a6-a6a6a6a6a6a6"),
                            ESPB = 0,
                            Naziv = "Računarske mreže"
                        },
                        new
                        {
                            Id = new Guid("a7a7a7a7-a7a7-a7a7-a7a7-a7a7a7a7a7a7"),
                            ESPB = 0,
                            Naziv = "Operativni sistemi"
                        },
                        new
                        {
                            Id = new Guid("a8a8a8a8-a8a8-a8a8-a8a8-a8a8a8a8a8a8"),
                            ESPB = 0,
                            Naziv = "Softversko inženjerstvo"
                        },
                        new
                        {
                            Id = new Guid("a9a9a9a9-a9a9-a9a9-a9a9-a9a9a9a9a9a9"),
                            ESPB = 0,
                            Naziv = "Veštačka inteligencija"
                        },
                        new
                        {
                            Id = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"),
                            ESPB = 0,
                            Naziv = "Mašinsko učenje"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            ESPB = 0,
                            Naziv = "Algoritmi i strukture podataka"
                        },
                        new
                        {
                            Id = new Guid("b3b3b3b3-b3b3-b3b3-b3b3-b3b3b3b3b3b3"),
                            ESPB = 0,
                            Naziv = "Matematička logika"
                        });
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.Profesor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profesori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "marko.markovic@gmail.com",
                            Ime = "Marko",
                            Prezime = "Marković"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "marko.markovic@gmail.com",
                            Ime = "Ana",
                            Prezime = "Anić"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "ana.anic@gmail.com",
                            Ime = "Ivan",
                            Prezime = "Ivanović"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "jelena.jelic@gmail.com",
                            Ime = "Jelena",
                            Prezime = "Jelić"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "petar.petrovic@gmail.com",
                            Ime = "Petar",
                            Prezime = "Petrović"
                        });
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.ProfesorPredmet", b =>
                {
                    b.Property<Guid>("ProfesorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PredmetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProfesorId", "PredmetId");

                    b.HasIndex("PredmetId");

                    b.ToTable("ProfesorPredmeti");

                    b.HasData(
                        new
                        {
                            ProfesorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PredmetId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1")
                        },
                        new
                        {
                            ProfesorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PredmetId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2")
                        },
                        new
                        {
                            ProfesorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PredmetId = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3")
                        },
                        new
                        {
                            ProfesorId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PredmetId = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4")
                        },
                        new
                        {
                            ProfesorId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PredmetId = new Guid("a5a5a5a5-a5a5-a5a5-a5a5-a5a5a5a5a5a5")
                        },
                        new
                        {
                            ProfesorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PredmetId = new Guid("a6a6a6a6-a6a6-a6a6-a6a6-a6a6a6a6a6a6")
                        },
                        new
                        {
                            ProfesorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PredmetId = new Guid("a7a7a7a7-a7a7-a7a7-a7a7-a7a7a7a7a7a7")
                        },
                        new
                        {
                            ProfesorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PredmetId = new Guid("a8a8a8a8-a8a8-a8a8-a8a8-a8a8a8a8a8a8")
                        });
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Smer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studenti");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ime = "Luka",
                            Index = "2021/0001",
                            Prezime = "Jovanović",
                            Smer = "IT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Ime = "Milica",
                            Index = "2021/0002",
                            Prezime = "Petrović",
                            Smer = "Menadžment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Ime = "Nikola",
                            Index = "2021/0003",
                            Prezime = "Nikolić",
                            Smer = "IT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Ime = "Jovana",
                            Index = "2021/0004",
                            Prezime = "Stojanović",
                            Smer = "Menadžment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Ime = "Stefan",
                            Index = "2021/0005",
                            Prezime = "Lazić",
                            Smer = "IT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Ime = "Ana",
                            Index = "2021/0006",
                            Prezime = "Đorđević",
                            Smer = "IT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Ime = "Filip",
                            Index = "2021/0007",
                            Prezime = "Ilić",
                            Smer = "Menadžment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Ime = "Tamara",
                            Index = "2021/0008",
                            Prezime = "Kovačević",
                            Smer = "IT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Ime = "Marko",
                            Index = "2021/0009",
                            Prezime = "Simić",
                            Smer = "Menadžment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Ime = "Sara",
                            Index = "2021/0010",
                            Prezime = "Mitrović",
                            Smer = "IT"
                        });
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.StudentPredmet", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PredmetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Ocena")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "PredmetId");

                    b.HasIndex("PredmetId");

                    b.ToTable("StudentPredmeti");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PredmetId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PredmetId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PredmetId = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PredmetId = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PredmetId = new Guid("a5a5a5a5-a5a5-a5a5-a5a5-a5a5a5a5a5a5"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PredmetId = new Guid("a6a6a6a6-a6a6-a6a6-a6a6-a6a6a6a6a6a6"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PredmetId = new Guid("a7a7a7a7-a7a7-a7a7-a7a7-a7a7a7a7a7a7"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PredmetId = new Guid("a8a8a8a8-a8a8-a8a8-a8a8-a8a8a8a8a8a8"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PredmetId = new Guid("a9a9a9a9-a9a9-a9a9-a9a9-a9a9a9a9a9a9"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PredmetId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PredmetId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PredmetId = new Guid("b3b3b3b3-b3b3-b3b3-b3b3-b3b3b3b3b3b3"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PredmetId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PredmetId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PredmetId = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PredmetId = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PredmetId = new Guid("a5a5a5a5-a5a5-a5a5-a5a5-a5a5a5a5a5a5"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PredmetId = new Guid("a6a6a6a6-a6a6-a6a6-a6a6-a6a6a6a6a6a6"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PredmetId = new Guid("a7a7a7a7-a7a7-a7a7-a7a7-a7a7a7a7a7a7"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PredmetId = new Guid("a8a8a8a8-a8a8-a8a8-a8a8-a8a8a8a8a8a8"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PredmetId = new Guid("a9a9a9a9-a9a9-a9a9-a9a9-a9a9a9a9a9a9"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PredmetId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PredmetId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PredmetId = new Guid("b3b3b3b3-b3b3-b3b3-b3b3-b3b3b3b3b3b3"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PredmetId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PredmetId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PredmetId = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PredmetId = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PredmetId = new Guid("a5a5a5a5-a5a5-a5a5-a5a5-a5a5a5a5a5a5"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PredmetId = new Guid("a6a6a6a6-a6a6-a6a6-a6a6-a6a6a6a6a6a6"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PredmetId = new Guid("a7a7a7a7-a7a7-a7a7-a7a7-a7a7a7a7a7a7"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PredmetId = new Guid("a8a8a8a8-a8a8-a8a8-a8a8-a8a8a8a8a8a8"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PredmetId = new Guid("a9a9a9a9-a9a9-a9a9-a9a9-a9a9a9a9a9a9"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PredmetId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PredmetId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PredmetId = new Guid("b3b3b3b3-b3b3-b3b3-b3b3-b3b3b3b3b3b3"),
                            Ocena = 9
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000010"),
                            PredmetId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Ocena = 6
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000010"),
                            PredmetId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            Ocena = 7
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000010"),
                            PredmetId = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3"),
                            Ocena = 8
                        },
                        new
                        {
                            StudentId = new Guid("00000000-0000-0000-0000-000000000010"),
                            PredmetId = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4"),
                            Ocena = 9
                        });
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.ProfesorPredmet", b =>
                {
                    b.HasOne("PukiAPI.Models.Domain.Predmet", "Predmet")
                        .WithMany("ProfesorPredmeti")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PukiAPI.Models.Domain.Profesor", "Profesor")
                        .WithMany("ProfesorPredmeti")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.StudentPredmet", b =>
                {
                    b.HasOne("PukiAPI.Models.Domain.Predmet", "Predmet")
                        .WithMany("StudentPredmeti")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PukiAPI.Models.Domain.Student", "Student")
                        .WithMany("StudentPredmeti")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.Predmet", b =>
                {
                    b.Navigation("ProfesorPredmeti");

                    b.Navigation("StudentPredmeti");
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.Profesor", b =>
                {
                    b.Navigation("ProfesorPredmeti");
                });

            modelBuilder.Entity("PukiAPI.Models.Domain.Student", b =>
                {
                    b.Navigation("StudentPredmeti");
                });
#pragma warning restore 612, 618
        }
    }
}
